# Generated by Django 5.0.7 on 2024-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_post_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_favorite",
            field=models.IntegerField(default=False),
        ),
    ]
