# Generated by Django 5.0.7 on 2024-08-03 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_post_app", "0004_remove_post_grade_favorite_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="average_mark",
        ),
    ]
