# Generated by Django 5.0.7 on 2024-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0003_rename_is_favorite_post_average_mark_post_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='grade',
        ),
        migrations.AddField(
            model_name='favorite',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
