# Generated by Django 5.0.7 on 2024-08-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0007_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
