# Generated by Django 5.0.7 on 2024-08-06 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0008_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='peoples_grade',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='post',
        ),
        migrations.AddField(
            model_name='favorite',
            name='posts',
            field=models.ManyToManyField(to='blog_post_app.post'),
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peoples_grade', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_post_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
